version: "3.8"
services:
  db:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./logs:/var/mysql
    # ports:
    #   - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    networks:
      - backend-db-network

volumes:
  mysql_data:

networks:
  backend-db-network:
    name: backend-db-network
    external: true
