services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/fullchain.pem:/ssl/fullchain.pem
      - ./ssl/privkey.pem:/ssl/privkey.pem
      - ./ssl/dhparam-2048.pem:/ssl/dhparam-2048.pem
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy-network

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PUBLIC_URL=https://intproj23.sit.kmutt.ac.th/us3/
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - proxy-network
      - backend-db-network

  frontend:
    build:
      context: ./frontend
      dockerfile: front.Dockerfile
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
  backend-db-network:
    name: backend-db-network
    external: true